apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calculator-chart.fullname" . }}
  labels:
    {{- include "calculator-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "calculator-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calculator-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
