replicaCount: 1

image:
  repository: antony28/sample_calc
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
