replicaCount: 1

image:
  repository: your-docker-repo/calculator-app
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
